version: "3.7"

services:
  rt:
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: rt5
      POSTGRES_USER: rt
      POSTGRES_PASSWORD: password
    volumes:
      - vol_db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - net

  phppgadmin:
    image: 'docker.io/bitnami/phppgadmin:7-debian-10'
    environment:
      DATABASE_HOST: "db"
    ports:
      - '127.0.0.1:8081:8080'
      - '127.0.0.1:8443:8443'
    depends_on:
      - db
    networks:
      - net

volumes:
  vol_db: {}
