version: "3.8"

services:
  rt:
    build:
      context: .
    image: firefart/requesttracker:latest
    restart: always
    deploy:
      mode: replicated
      replicas: 5
    volumes:
      - ./RT_SiteConfig.pm:/opt/rt5/etc/RT_SiteConfig.pm:ro
      - ./msmtp/msmtp.conf:/etc/msmtprc:ro
      - ./msmtp/:/msmtp:ro
      - ./getmail/getmailrc:/getmail/getmailrc:ro
      - ./gpg/:/opt/rt5/var/data/gpg
      - ./smime/:/opt/rt5/var/data/smime
      - /etc/localtime:/etc/localtime:ro
    # make the host available inside the image
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - net

  cron:
    build:
      context: .
    image: firefart/requesttracker:latest
    restart: always
    # the cron daemon needs to run as root
    user: root
    # this will run the busybox crond
    command: [ "/usr/sbin/crond", "-f", "-l", "8" ]
    # no need for tini here
    entrypoint: ""
    depends_on:
      - rt
      # we send rt-mailgate over to nginx
      - nginx
    volumes:
      - ./RT_SiteConfig.pm:/opt/rt5/etc/RT_SiteConfig.pm:ro
      - ./msmtp/msmtp.conf:/etc/msmtprc:ro
      - ./msmtp/:/msmtp:ro
      - ./getmail/getmailrc:/getmail/getmailrc:ro
      - ./gpg/:/opt/rt5/var/data/gpg
      - ./smime/:/opt/rt5/var/data/smime
      - ./crontab:/var/spool/cron/crontabs/rt:ro
      - ./cron/:/cron
      - /etc/localtime:/etc/localtime:ro
    # make the host available inside the image
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - net

  nginx:
    build:
      context: nginx
    image: firefart/requesttracker:nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - rt
    volumes:
      - ./nginx/certs/:/certs/:ro
      - ./nginx/startup-scripts/:/docker-entrypoint.d/:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - net

networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_rt
