services:
  rt:
    build:
      context: .
    image: firefart/requesttracker:latest
    restart: always
    deploy:
      mode: replicated
      replicas: 5
      endpoint_mode: vip
    volumes:
      - ./RT_SiteConfig.pm:/opt/rt5/etc/RT_SiteConfig.pm:ro
      - ./msmtp/msmtp.conf:/etc/msmtprc:ro
      - ./msmtp/:/msmtp:ro
      - ./getmail/getmailrc:/getmail/getmailrc:ro
      - ./gpg/:/opt/rt5/var/data/gpg
      - ./smime/:/opt/rt5/var/data/smime
      - ./shredder/:/opt/rt5/var/data/RT-Shredder
      - /etc/localtime:/etc/localtime:ro
    # make the host available inside the image
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - net

  cron:
    build:
      context: .
    image: firefart/requesttracker:latest
    restart: always
    # the cron daemon needs to run as root
    user: root
    command: ["/root/cron_entrypoint.sh"]
    # no need for tini here
    entrypoint: ""
    # disable the healthcheck from the main dockerfile
    healthcheck:
      disable: true
    depends_on:
      rt:
        condition: service_healthy
        restart: true
      # we send rt-mailgate over to nginx
      nginx:
        condition: service_healthy
        restart: true
    volumes:
      - ./RT_SiteConfig.pm:/opt/rt5/etc/RT_SiteConfig.pm:ro
      - ./msmtp/msmtp.conf:/etc/msmtprc:ro
      - ./msmtp/:/msmtp:ro
      - ./getmail/getmailrc:/getmail/getmailrc:ro
      - ./gpg/:/opt/rt5/var/data/gpg
      - ./smime/:/opt/rt5/var/data/smime
      - ./crontab:/root/crontab:ro # needed so we can add it ro. Permissions are changed in startup script
      - ./cron/:/cron
      - ./shredder/:/opt/rt5/var/data/RT-Shredder
      - /etc/localtime:/etc/localtime:ro
    # make the host available inside the image
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - net

  nginx:
    build:
      context: nginx
    image: firefart/requesttracker:nginx-latest
    ports:
      - "0.0.0.0:443:443"
      - "127.0.0.1:8080:8080" # expose mailgate vhost to host
    # uncomment to enable debug mode
    # command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      rt:
        condition: service_healthy
        restart: true
      dozzle:
        condition: service_healthy
        restart: true
      pgadmin:
        condition: service_healthy
        restart: true
    volumes:
      - ./nginx/certs/:/certs/:ro
      - ./nginx/startup-scripts/:/docker-entrypoint.d/:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - net

  dozzle:
    image: amir20/dozzle:latest
    profiles:
      - full
    restart: always
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - DOZZLE_BASE=${DOZZLE_BASE:-/logs}
      - DOZZLE_NO_ANALYTICS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net

  pgadmin:
    image: dpage/pgadmin4:latest
    profiles:
      - full
    restart: always
    environment:
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-root@root.com}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
      PGADMIN_DISABLE_POSTFIX: disable
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://127.0.0.1:80/misc/ping"]
      interval: 10s
      timeout: 10s
      start_period: 160s
      retries: 3
    secrets:
      - pgadmin_password
    volumes:
      - vol_pgadmin:/var/lib/pgadmin
    networks:
      - net

secrets:
  pgadmin_password:
    file: ./pgadmin_password.secret

volumes:
  vol_pgadmin: {}

networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_rt
