services:
  rt:
    build:
      args:
        ADDITIONAL_CPANM_ARGS: "-n" # disable tests in dev to speed up builds
    restart: "no"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:

  cron:
    build:
      args:
        ADDITIONAL_CPANM_ARGS: "-n" # disable tests in dev to speed up builds
    restart: "no"


  nginx:
    restart: "no"

volumes:
