version: "3"

services:
  rt:
    build:
      args:
        ADDITIONAL_CPANM_ARGS: "-n" # disable tests in dev to speed up builds
    restart: "no"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      db:
        condition: service_healthy
        restart: true

  cron:
    build:
      args:
        ADDITIONAL_CPANM_ARGS: "-n" # disable tests in dev to speed up builds
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
        restart: true

  nginx:
    restart: "no"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: rt
      POSTGRES_USER: rt
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "rt"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - vol_db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - net

  dozzle:
    restart: "no"

  pgadmin:
    restart: "no"

volumes:
  vol_db: {}
