name: Build Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  images:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v2.3.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push RT
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: firefart/requesttracker:latest

      - name: Build and push NGINX
        uses: docker/build-push-action@v2
        with:
          context: ./nginx/
          push: true
          tags: firefart/requesttracker:nginx
